// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4LKCQKbulmUjQPkaA_e3iu3u-MIFjmJM',
    appId: '1:673317344443:web:273f273cb4fe940853459e',
    messagingSenderId: '673317344443',
    projectId: 'sahabatsenja',
    authDomain: 'sahabatsenja.firebaseapp.com',
    storageBucket: 'sahabatsenja.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9EUR4pPEVUrsURRArGhBP40tqDqjngVE',
    appId: '1:673317344443:android:3efc90d4b6397a5253459e',
    messagingSenderId: '673317344443',
    projectId: 'sahabatsenja',
    storageBucket: 'sahabatsenja.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxMa8FQWANB4UODqCMb2TIt--mla7h6yE',
    appId: '1:673317344443:ios:58f8a807afe29dfc53459e',
    messagingSenderId: '673317344443',
    projectId: 'sahabatsenja',
    storageBucket: 'sahabatsenja.firebasestorage.app',
    iosBundleId: 'com.example.sahabatsenjaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxMa8FQWANB4UODqCMb2TIt--mla7h6yE',
    appId: '1:673317344443:ios:58f8a807afe29dfc53459e',
    messagingSenderId: '673317344443',
    projectId: 'sahabatsenja',
    storageBucket: 'sahabatsenja.firebasestorage.app',
    iosBundleId: 'com.example.sahabatsenjaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4LKCQKbulmUjQPkaA_e3iu3u-MIFjmJM',
    appId: '1:673317344443:web:a165e1fbf9d159bc53459e',
    messagingSenderId: '673317344443',
    projectId: 'sahabatsenja',
    authDomain: 'sahabatsenja.firebaseapp.com',
    storageBucket: 'sahabatsenja.firebasestorage.app',
  );
}
